<h1><?= $this->translate('A 404 error occurred') ?></h1>
<h2><?= $this->message ?></h2>

<?php if(isset($this->reason) && $this->reason) : ?>
    <?php
    $reasonMessage= '';
    switch ($this->reason) :
        case 'error-controller-cannot-dispatch':
            $reasonMessage = $this->translate('The requested controller was unable to dispatch the request.');
            break;
        case 'error-controller-not-found':
            $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
            break;
        case 'error-controller-invalid':
            $reasonMessage = $this->translate('The requested controller was not dispatchable.');
            break;
        case 'error-router-no-match':
            $reasonMessage = $this->translate('The requested URL could not be matched by routing.');
            break;
        default:
            $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
            break;
    endswitch ?>
    <p><?= $reasonMessage ?></p>
<?php endif ?>

<?php if(isset($this->controller) && $this->controller) : ?>
    <dl>
        <dt><?= ucfirst($this->translatePlural('controller', 'controllers', 1)) ?>:</dt>
        <dd><?= $this->escapeHtml($this->controller) ?>
            <?php if(isset($this->controller_class)
                && $this->controller_class
                && $this->controller_class != $this->controller
            ) :
                echo '(' . sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
            endif ?>
        </dd>
    </dl>
<?php endif ?>

<?php if(isset($this->display_exceptions) && $this->display_exceptions) : ?>
    <?php if(isset($this->exception) && $this->exception instanceof Exception) : ?>
        <hr/>
        <h2><?= ucfirst($this->translatePlural('additional information', 'additional informations', 1)) ?>:</h2>
        <h3><?= get_class($this->exception) ?></h3>
        <dl>
            <dt><?= ucfirst($this->translatePlural('file', 'files', 1)) ?>:</dt>
            <dd><pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre></dd>
            <dt><?= ucfirst($this->translatePlural('message', 'messages', 1)) ?>:</dt>
            <dd><pre class="prettyprint linenums"><?= $this->exception->getMessage() ?></pre></dd>
            <dt><?= ucfirst($this->translate('stack trace')) ?>:</dt>
            <dd><pre class="prettyprint linenums"><?= $this->exception->getTraceAsString() ?></pre></dd>
        </dl>
        <?php
        $e = $this->exception->getPrevious();
        $icount = 0;
        if($e) : ?>
            <hr/>
            <h2><?= ucfirst($this->translatePlural('previous exception', 'previous exceptions', 2)) ?>:</h2>
            <ul class="unstyled">
                <?php while($e) : ?>
                    <li>
                        <h3><?= get_class($e) ?></h3>
                        <dl>
                            <dt><?= ucfirst($this->translatePlural('file', 'files', 1)) ?>:</dt>
                            <dd><pre class="prettyprint linenums"><?= $e->getFile() ?>:<?= $e->getLine() ?></pre></dd>
                            <dt><?= ucfirst($this->translatePlural('message', 'messages', 1)) ?>:</dt>
                            <dd><pre class="prettyprint linenums"><?= $e->getMessage() ?></pre></dd>
                            <dt><?= $this->translate('stack trace') ?>:</dt>
                            <dd><pre class="prettyprint linenums"><?= $e->getTraceAsString() ?></pre></dd>
                        </dl>
                    </li>
                    <?php
                    $e = $e->getPrevious();
                    $icount += 1;
                    if ($icount >=50) :
                        echo sprintf("<li>%s</li>", $this->translate('There may be more exceptions, but we have no enough memory to proccess it.'));
                        break;
                    endif;
                endwhile ?>
            </ul>
        <?php endif ?>
    <?php else : ?>
        <h3><?= $this->translate('No Exception available') ?></h3>
    <?php endif ?>
<?php endif ?>
