<h1><?= $this->translate('An error occurred') ?></h1>
<h2><?= $this->message ?></h2>

<?php if(isset($this->display_exceptions) && $this->display_exceptions) : ?>
    <?php if(isset($this->exception) && $this->exception instanceof Exception) : ?>
        <hr/>
        <h2><?= ucfirst($this->translatePlural('additional information', 'additional informations', 1)) ?>:</h2>
        <h3><?= get_class($this->exception) ?></h3>
        <dl>
            <dt><?= ucfirst($this->translatePlural('file', 'files', 1)) ?>:</dt>
            <dd><pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre></dd>
            <dt><?= ucfirst($this->translatePlural('message', 'messages', 1)) ?>:</dt>
            <dd><pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getMessage()) ?></pre></dd>
            <dt><?= ucfirst($this->translate('stack trace')) ?>:</dt>
            <dd><pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre></dd>
        </dl>
        <?php
        $e = $this->exception->getPrevious();
        $icount = 0;
        if($e) : ?>
            <hr/>
            <h2><?= ucfirst($this->translatePlural('previous exception', 'previous exceptions', 2)) ?>:</h2>
            <ul class="unstyled">
                <?php while($e) : ?>
                    <li>
                        <h3><?= get_class($e) ?></h3>
                        <dl>
                            <dt><?= ucfirst($this->translatePlural('file', 'files', 1)) ?>:</dt>
                            <dd><pre class="prettyprint linenums"><?= $e->getFile() ?>:<?= $e->getLine() ?></pre></dd>
                            <dt><?= ucfirst($this->translatePlural('message', 'messages', 1)) ?>:</dt>
                            <dd><pre class="prettyprint linenums"><?= $this->escapeHtml($e->getMessage()) ?></pre></dd>
                            <dt><?= ucfirst($this->translate('stack trace')) ?>:</dt>
                            <dd><pre class="prettyprint linenums"><?= $this->escapeHtml($e->getTraceAsString()) ?></pre></dd>
                        </dl>
                    </li>
                    <?php
                    $e = $e->getPrevious();
                    $icount += 1;
                    if($icount >= 50) :
                        echo sprintf("<li>%s</li>", $this->translate('There may be more exceptions, but we have no enough memory to proccess it.'));
                        break;
                    endif ?>
                <?php endwhile ?>
            </ul>
        <?php endif ?>
    <?php else : ?>
        <h3><?= $this->translate('No Exception available') ?></h3>
    <?php endif ?>
<?php endif ?>
