<?php
/** doctype */
echo $this->doctype();
/** title */
$this->headTitle('Aist ZF2')->setSeparator(' - ')->setAutoEscape(false);
/** meta */
$this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ->setCharset('utf-8')
;
/** styles */
$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
    ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
;
/** scripts */
$this->headScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
    ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
;
?>
<html lang="en">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?= $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2006 - <?= date('Y') ?> by Aist Internet Technologies <?= $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
